<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["tbl_test/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["tbl_test/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Uint Of Test Of Index</th>
            <th>Uint Of Test Of Type</th>
            <th>Uint Of Test Of Mode</th>
            <th>Text Of Test Of Description</th>
            <th>Char Of Test Of Name</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $tbl_test): ?>
            <tr>
                <td><?php echo $tbl_test->uint_test_index ?></td>
            <td><?php echo $tbl_test->uint_test_type ?></td>
            <td><?php echo $tbl_test->uint_test_mode ?></td>
            <td><?php echo $tbl_test->text_test_description ?></td>
            <td><?php echo $tbl_test->char_test_name ?></td>

                <td><?php echo $this->tag->linkTo(["tbl_test/edit/" . $tbl_test->uint_test_index, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["tbl_test/delete/" . $tbl_test->uint_test_index, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("tbl_test/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("tbl_test/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("tbl_test/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("tbl_test/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
