<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["tbl_slot_config", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit tbl_slot_config
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "tbl_slot_config/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldRackName" class="col-sm-2 control-label">Rack Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["rack_name", "size" => 30, "class" => "form-control", "id" => "fieldRackName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRackNumber" class="col-sm-2 control-label">Rack Of Number</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["rack_number", "type" => "number", "class" => "form-control", "id" => "fieldRackNumber"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUintSlotAvailability" class="col-sm-2 control-label">Uint Of Slot Of Availability</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_slot_availability", "type" => "number", "class" => "form-control", "id" => "fieldUintSlotAvailability"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUintBoxIndex" class="col-sm-2 control-label">Uint Of Box Of Index</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_box_index", "type" => "number", "class" => "form-control", "id" => "fieldUintBoxIndex"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUintRackType" class="col-sm-2 control-label">Uint Of Rack Of Type</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_rack_type", "type" => "number", "class" => "form-control", "id" => "fieldUintRackType"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
