<?php

/**
 * Cidt
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-12-16, 17:01:19
 */

namespace citesting;

use Phalcon\Mvc\Model;
use Phalcon\Mvc\Model\Message;
use Phalcon\Mvc\Model\Validator\Uniqueness;
use Phalcon\Mvc\Model\Validator\InclusionIn;

class Cidt extends Model
{


    /**
     *
     * @var string
     * @Column(type="string", length=45, nullable=false)
     */
    public $JobId;

    /**
     *
     * @var string
     * @Column(type="string", length=15, nullable=false)
     */
    public $Platform;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $Priority;

    /**
     *
     * @var string
     * @Column(type="string", length=25, nullable=false)
     */
    public $Status;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    public $JobNumber;

    /**
     *
     * @var string
     * @Column(type="string", length=45, nullable=true)
     */
    public $JobName;

    /**
     * @return bool
     */
    public function validation()
    {

        /*

        // Robot name must be unique
        $this->validate(

            new Uniqueness(
                [
                    "field"   => "JobId",
                    "message" => "The JobId must be unique",
                ]
            )


        );

        // Check if any messages have been produced
        if ($this->validationHasFailed() === true) {
            return false;
        }
        */
        return true;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("cisystem");
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'cidt';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Cidt[]|Cidt
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Cidt
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
