<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["tbl_build_details/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["tbl_build_details/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Uint Of Build Of Index</th>
            <th>Char Of Build Of Name</th>
            <th>Uint Of Box Of Platform</th>
            <th>Char Of Build Of Md5sum</th>
            <th>Uint Of Build Of Type</th>
            <th>Char Of Middleware Of Version</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $tbl_build_detail): ?>
            <tr>
                <td><?php echo $tbl_build_detail->uint_build_index ?></td>
            <td><?php echo $tbl_build_detail->char_build_name ?></td>
            <td><?php echo $tbl_build_detail->uint_box_platform ?></td>
            <td><?php echo $tbl_build_detail->char_build_md5sum ?></td>
            <td><?php echo $tbl_build_detail->uint_build_type ?></td>
            <td><?php echo $tbl_build_detail->char_middleware_version ?></td>

                <td><?php echo $this->tag->linkTo(["tbl_build_details/edit/" . $tbl_build_detail->uint_build_index, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["tbl_build_details/delete/" . $tbl_build_detail->uint_build_index, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("tbl_build_details/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("tbl_build_details/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("tbl_build_details/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("tbl_build_details/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
