<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["cift", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit cift
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "cift/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldJobid" class="col-sm-2 control-label">JobId</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["JobId", "size" => 30, "class" => "form-control", "id" => "fieldJobid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPlatform" class="col-sm-2 control-label">Platform</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Platform", "size" => 30, "class" => "form-control", "id" => "fieldPlatform"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPriority" class="col-sm-2 control-label">Priority</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Priority", "type" => "number", "class" => "form-control", "id" => "fieldPriority"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTestlistname" class="col-sm-2 control-label">TestListName</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["TestListName", "size" => 30, "class" => "form-control", "id" => "fieldTestlistname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldJobnumber" class="col-sm-2 control-label">JobNumber</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["JobNumber", "type" => "number", "class" => "form-control", "id" => "fieldJobnumber"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStatus" class="col-sm-2 control-label">Status</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["Status", "size" => 30, "class" => "form-control", "id" => "fieldStatus"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
