<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["cidt/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["cidt/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>JobId</th>
            <th>Platform</th>
            <th>Priority</th>
            <th>Status</th>
            <th>JobNumber</th>
            <th>JobName</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $cidt): ?>
            <tr>
                <td><?php echo $cidt->JobId ?></td>
            <td><?php echo $cidt->Platform ?></td>
            <td><?php echo $cidt->Priority ?></td>
            <td><?php echo $cidt->Status ?></td>
            <td><?php echo $cidt->JobNumber ?></td>
            <td><?php echo $cidt->JobName ?></td>

                <td><?php echo $this->tag->linkTo(["cidt/edit/" . $cidt->JobId, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["cidt/delete/" . $cidt->JobId, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("cidt/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("cidt/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("cidt/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("cidt/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
