<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search tbl_box_details
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["tbl_box_details/new", "Create tbl_box_details"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "tbl_box_details/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldUintBoxIndex" class="col-sm-2 control-label">Uint Of Box Of Index</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_box_index", "type" => "number", "class" => "form-control", "id" => "fieldUintBoxIndex"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCharBoxIp" class="col-sm-2 control-label">Char Of Box Of Ip</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["char_box_ip", "size" => 30, "class" => "form-control", "id" => "fieldCharBoxIp"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUintBoxPlatform" class="col-sm-2 control-label">Uint Of Box Of Platform</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_box_platform", "type" => "number", "class" => "form-control", "id" => "fieldUintBoxPlatform"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCharMac" class="col-sm-2 control-label">Char Of Mac</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["char_mac", "size" => 30, "class" => "form-control", "id" => "fieldCharMac"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
