<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["tbl_job_execution_status/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["tbl_job_execution_status/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Unit Of Job Of Execution Of Status</th>
            <th>Uint Of Job</th>
            <th>Uint Of Slot Of Index</th>
            <th>Datetime Of Test Of Start</th>
            <th>Datetime Of Test Of Finish</th>
            <th>Uint Of Execution Of Status</th>
            <th>Text Of Msg</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $tbl_job_execution_statu): ?>
            <tr>
                <td><?php echo $tbl_job_execution_statu->unit_job_execution_status ?></td>
            <td><?php echo $tbl_job_execution_statu->uint_job_id ?></td>
            <td><?php echo $tbl_job_execution_statu->uint_slot_index ?></td>
            <td><?php echo $tbl_job_execution_statu->datetime_test_start ?></td>
            <td><?php echo $tbl_job_execution_statu->datetime_test_finish ?></td>
            <td><?php echo $tbl_job_execution_statu->uint_execution_status ?></td>
            <td><?php echo $tbl_job_execution_statu->text_msg ?></td>

                <td><?php echo $this->tag->linkTo(["tbl_job_execution_status/edit/" . $tbl_job_execution_statu->unit_job_execution_status, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["tbl_job_execution_status/delete/" . $tbl_job_execution_statu->unit_job_execution_status, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("tbl_job_execution_status/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("tbl_job_execution_status/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("tbl_job_execution_status/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("tbl_job_execution_status/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
