<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search tbl_monitoring_task_seq_of_test
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["tbl_monitoring_task_seq_of_test/new", "Create tbl_monitoring_task_seq_of_test"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "tbl_monitoring_task_seq_of_test/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldUintMonitrorTestMappingIndex" class="col-sm-2 control-label">Uint Of Monitror Of Test Of Mapping Of Index</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_monitror_test_mapping_index", "type" => "number", "class" => "form-control", "id" => "fieldUintMonitrorTestMappingIndex"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUintInternalqMappingIndex" class="col-sm-2 control-label">Uint Of InternalQ Of Mapping Of Index</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_internalQ_mapping_index", "type" => "number", "class" => "form-control", "id" => "fieldUintInternalqMappingIndex"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUintMonitorTaskSeqOrder" class="col-sm-2 control-label">Uint Of Monitor Of Task Of Seq Of Order</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_monitor_task_seq_order", "type" => "number", "class" => "form-control", "id" => "fieldUintMonitorTaskSeqOrder"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUintMonitorTestIndex" class="col-sm-2 control-label">Uint Of Monitor Of Test Of Index</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_monitor_test_index", "type" => "number", "class" => "form-control", "id" => "fieldUintMonitorTestIndex"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTimeMonitorTestWait" class="col-sm-2 control-label">Time Of Monitor Of Test Of Wait</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_monitor_test_wait", "size" => 30, "class" => "form-control", "id" => "fieldTimeMonitorTestWait"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDatetimeMonitorTestStart" class="col-sm-2 control-label">Datetime Of Monitor Of Test Of Start</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["datetime_monitor_test_start", "size" => 30, "class" => "form-control", "id" => "fieldDatetimeMonitorTestStart"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDatetimeMonitorTestFinish" class="col-sm-2 control-label">Datetime Of Monitor Of Test Of Finish</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["datetime_monitor_test_finish", "size" => 30, "class" => "form-control", "id" => "fieldDatetimeMonitorTestFinish"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUintMonitorTestStatus" class="col-sm-2 control-label">Uint Of Monitor Of Test Of Status</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_monitor_test_status", "type" => "number", "class" => "form-control", "id" => "fieldUintMonitorTestStatus"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTextErrorDescription" class="col-sm-2 control-label">Text Of Error Of Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["text_error_description", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldTextErrorDescription"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
