<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search tbl_slot_config
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["tbl_slot_config/new", "Create tbl_slot_config"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "tbl_slot_config/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldUintSlotIndex" class="col-sm-2 control-label">Uint Of Slot Of Index</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_slot_index", "type" => "number", "class" => "form-control", "id" => "fieldUintSlotIndex"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRackName" class="col-sm-2 control-label">Rack Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["rack_name", "size" => 30, "class" => "form-control", "id" => "fieldRackName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRackNumber" class="col-sm-2 control-label">Rack Of Number</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["rack_number", "type" => "number", "class" => "form-control", "id" => "fieldRackNumber"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBoolSlotAvailability" class="col-sm-2 control-label">Bool Of Slot Of Availability</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["bool_slot_availability", "size" => 30, "class" => "form-control", "id" => "fieldBoolSlotAvailability"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUintBoxIndex" class="col-sm-2 control-label">Uint Of Box Of Index</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_box_index", "type" => "number", "class" => "form-control", "id" => "fieldUintBoxIndex"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUintRackType" class="col-sm-2 control-label">Uint Of Rack Of Type</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_rack_type", "type" => "number", "class" => "form-control", "id" => "fieldUintRackType"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
