<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["tbl_slot_config/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["tbl_slot_config/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Uint Of Slot Of Index</th>
            <th>Rack Of Name</th>
            <th>Rack Of Number</th>
            <th>Bool Of Slot Of Availability</th>
            <th>Uint Of Box Of Index</th>
            <th>Uint Of Rack Of Type</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $tbl_slot_config): ?>
            <tr>
                <td><?php echo $tbl_slot_config->uint_slot_index ?></td>
            <td><?php echo $tbl_slot_config->rack_name ?></td>
            <td><?php echo $tbl_slot_config->rack_number ?></td>
            <td><?php echo $tbl_slot_config->bool_slot_availability ?></td>
            <td><?php echo $tbl_slot_config->uint_box_index ?></td>
            <td><?php echo $tbl_slot_config->uint_rack_type ?></td>

                <td><?php echo $this->tag->linkTo(["tbl_slot_config/edit/" . $tbl_slot_config->uint_slot_index, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["tbl_slot_config/delete/" . $tbl_slot_config->uint_slot_index, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("tbl_slot_config/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("tbl_slot_config/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("tbl_slot_config/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("tbl_slot_config/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
