<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search tbl_internal_queue
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["tbl_internal_queue/new", "Create tbl_internal_queue"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "tbl_internal_queue/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldUintInternalqMappingIndex" class="col-sm-2 control-label">Uint Of InternalQ Of Mapping Of Index</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_internalQ_mapping_index", "type" => "number", "class" => "form-control", "id" => "fieldUintInternalqMappingIndex"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUintJobId" class="col-sm-2 control-label">Uint Of Job</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_job_id", "type" => "number", "class" => "form-control", "id" => "fieldUintJobId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUintSeqOrder" class="col-sm-2 control-label">Uint Of Seq Of Order</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_seq_order", "type" => "number", "class" => "form-control", "id" => "fieldUintSeqOrder"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUintTestIndex" class="col-sm-2 control-label">Uint Of Test Of Index</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["uint_test_index", "type" => "number", "class" => "form-control", "id" => "fieldUintTestIndex"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
