<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["tbl_internal_queue/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["tbl_internal_queue/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Uint Of InternalQ Of Mapping Of Index</th>
            <th>Uint Of Job</th>
            <th>Uint Of Seq Of Order</th>
            <th>Uint Of Test Of Index</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $tbl_internal_queue): ?>
            <tr>
                <td><?php echo $tbl_internal_queue->uint_internalQ_mapping_index ?></td>
            <td><?php echo $tbl_internal_queue->uint_job_id ?></td>
            <td><?php echo $tbl_internal_queue->uint_seq_order ?></td>
            <td><?php echo $tbl_internal_queue->uint_test_index ?></td>

                <td><?php echo $this->tag->linkTo(["tbl_internal_queue/edit/" . $tbl_internal_queue->uint_internalQ_mapping_index, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["tbl_internal_queue/delete/" . $tbl_internal_queue->uint_internalQ_mapping_index, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("tbl_internal_queue/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("tbl_internal_queue/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("tbl_internal_queue/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("tbl_internal_queue/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
